In [5]:
# OpenCV-python のインポート
import cv2
import numpy as np

In [11]:
path = "../data"

# OpenCV-pythonのインポート
# お試しで２枚読み込ませます
img_1 = cv2.imread(path + "/広島風お好み焼き.jpg", cv2.IMREAD_COLOR)
img_2 = cv2.imread(path + "/いちごとシャンパン.jpg", cv2.IMREAD_COLOR)

In [12]:
print(type(img_1))
# 多次元配列であることがわかります

print(img_1.shape)
print(img_1)

<class 'numpy.ndarray'>
(4032, 3024, 3)
[[[138 148 158]
  [134 144 154]
  [137 147 157]
  ...
  [ 76  90 112]
  [ 76  90 109]
  [ 72  86 105]]

 [[138 148 158]
  [137 147 157]
  [135 145 155]
  ...
  [ 76  90 112]
  [ 79  93 112]
  [ 78  92 111]]

 [[136 146 156]
  [140 150 160]
  [136 146 156]
  ...
  [ 77  94 115]
  [ 75  90 109]
  [ 72  87 106]]

 ...

 [[ 32  64 100]
  [ 34  66 102]
  [ 33  65 101]
  ...
  [ 61 102 141]
  [ 62 101 140]
  [ 63 102 141]]

 [[ 29  61  97]
  [ 32  64 100]
  [ 32  64 100]
  ...
  [ 61 100 139]
  [ 54  93 132]
  [ 54  93 132]]

 [[ 31  63  99]
  [ 33  65 101]
  [ 31  63  99]
  ...
  [ 52  91 130]
  [ 49  88 127]
  [ 54  93 132]]]
